# Languages
# Create a section for each of your site's languages.
# Documentation: https://docs.hugoblox.com/reference/language/

# 기본 언어 설정 (한국어를 기본으로 설정)
ko:
  languageCode: ko
  contentDir: content/ko  # 한국어 콘텐츠 폴더
  title: 사이트 한국어 제목
  params:
    description: 사이트 한국어 설명
  menu:
    main:
      - name: 소개
        url: '#admin'
        weight: 1

# 추가 언어 (영어 설정)
en:
  languageCode: en-us
  contentDir: content/en  # 영어 콘텐츠 폴더
  title: English Website Title
  params:
    description: Site description in English
  menu:
    main:
      - name: About
        url: '#admin'
        weight: 1
