languages:
  ko:
    weight: 1  # This gives priority to the 'ko' language
    languageName: 한국어
    contentDir: content/ko
    title: '사이트 제목 한국어'  # Site title in Korean
    params:
      description: '한국어 사이트 설명'  # Site description in Korean

  en:
    weight: 2  # English is set as secondary
    languageName: English
    contentDir: content/en
    title: 'Site Title English'
    params:
      description: 'English site description'
