defaultContentLanguage: ko  # 기본 언어를 한국어로 설정
languages:
  ko:
    languageName: 한국어
    contentDir: content/ko
    weight: 1  # 한국어를 기본 언어로 설정
  en:
    languageName: English
    contentDir: content/en
    weight: 2  # 영어를 보조 언어로 설정
