# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language (English)
en:
  languageCode: en-us
  title: My Blog
  params:
    description: Description of my blog...
  contentDir: content/en
  menu:
    main:
      - name: Home
        url: '/'
        weight: 1
      - name: About
        url: '#about'
        weight: 2

# Korean language settings (한국어)
ko:
  languageCode: ko
  title: 내 블로그
  params:
    description: 나만의 블로그 설명...
  contentDir: content/ko
  menu:
    main:
      - name: 홈
        url: '/'
        weight: 1
      - name: 소개
        url: '#about'
        weight: 2
