# Navigation Links
main:
  - name: Introduce
    url: /
    weight: 10
  - name: error
    url: /error
    weight: 14
  - name: event
    url: /event
    weight: 14
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: contect
    url: /contect
    weight: 50
    children:  # 서브메뉴를 추가하는 부분
      - name: 안녕
        url: /contect/hello  # 서브메뉴 링크
        weight: 90  # 서브메뉴의 순서
