main:
  - name: People
    url: people
    weight: 200
  - parent: People
    name: My
    url: /author/강경태/
    weight: 210
  - parent: People
    name: Animal
    url: people
    weight: 220

  - name: Passions & Projects
    url: publication
    weight: 300
  - parent: Passions & Projects
    name: Interests & Hobbies
    url: publication
    weight: 310
  - parent: Passions & Projects
    name: My Projects
    url: field
    weight: 320

  - name: Campus Life
    url: publication
    weight: 330
  - parent: Campus Life
    name: Awards & Achievements
    url: /Campus Life/Awards/
    weight: 340
  - parent: Campus Life
    name: Extracurricular Activities
    url: /Campus Life/Activities/
    weight: 350

  - name: Inform
    url: post
    weight: 600
  - parent: Inform
    name: Notifications
    url: notification
    weight: 610
  - parent: Inform
    name: News
    url: post
    weight: 620
  - parent: Inform
    name: Event
    url: event
    weight: 630

  - name: Information
    url: information
    weight: 800
  - parent: Information
    name: About
    url: about
    weight: 810
  - parent: Information
    name: Contact
    url: contact
    weight: 820
